name: socialmedia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  fluttertoast: ^8.2.8
  persistent_bottom_nav_bar: ^6.2.1
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  firebase_auth: ^5.3.1
  flutter_gen: ^5.7.0
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.4.4
  phone_input: ^1.0.0
  csc_picker: ^0.2.7
  flutter_card_swiper: ^7.0.1
  palette_generator: ^0.3.3+4
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.3.1
  record: ^5.1.2
  just_audio: ^0.9.41
  path_provider: ^2.1.4
  voice_message_package: 
    path: ./lib/speech/voice_message_package-2.2.1/
  http: ^1.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_image_compress: ^2.3.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:



flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF-Pro-Display-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
    - family: SF-Pro-Display-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family:  SF-Pro-Display-Light
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf

    - family:  SF-Pro-Display-Medium
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
