// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCATZy_oLhiY7aGo8uJ07FmPXCGlw1AxZw',
    appId: '1:694060209372:web:83288b66a4820963c9d019',
    messagingSenderId: '694060209372',
    projectId: 'socialmedia-5c321',
    authDomain: 'socialmedia-5c321.firebaseapp.com',
    storageBucket: 'socialmedia-5c321.appspot.com',
    measurementId: 'G-NZF9TNR39B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5bkedr3ciglU-n6c1Z4fBUO32I4vq9J8',
    appId: '1:694060209372:android:db69e6476588eeb7c9d019',
    messagingSenderId: '694060209372',
    projectId: 'socialmedia-5c321',
    storageBucket: 'socialmedia-5c321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2PVgwr47iTBUTyi-zE6tPtBuJwoKKe8g',
    appId: '1:694060209372:ios:d81fc40cc315c9f5c9d019',
    messagingSenderId: '694060209372',
    projectId: 'socialmedia-5c321',
    storageBucket: 'socialmedia-5c321.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2PVgwr47iTBUTyi-zE6tPtBuJwoKKe8g',
    appId: '1:694060209372:ios:d81fc40cc315c9f5c9d019',
    messagingSenderId: '694060209372',
    projectId: 'socialmedia-5c321',
    storageBucket: 'socialmedia-5c321.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCATZy_oLhiY7aGo8uJ07FmPXCGlw1AxZw',
    appId: '1:694060209372:web:033e5685f0248cabc9d019',
    messagingSenderId: '694060209372',
    projectId: 'socialmedia-5c321',
    authDomain: 'socialmedia-5c321.firebaseapp.com',
    storageBucket: 'socialmedia-5c321.appspot.com',
    measurementId: 'G-SNX72BYSSQ',
  );
}
